In [1]:
import pandas as pd
import numpy as np
from os import mkdir
from os.path import exists, dirname, join
import jinja2

In [3]:
jinja_env = jinja2.Environment(
        loader=jinja2.FileSystemLoader("."),
        trim_blocks=True,
        lstrip_blocks=True)

In [20]:
df = pd.read_excel('Listado_Jovenes_alaU_28022024.xlsx')

In [36]:
df.describe

<bound method NDFrame.describe of      COD_FACULTAD                                          FACULTAD  \
0             101                            FACULTAD DE ARTES-ASAB
1             101                            FACULTAD DE ARTES-ASAB
2             101                            FACULTAD DE ARTES-ASAB
3             101                            FACULTAD DE ARTES-ASAB
4             101                            FACULTAD DE ARTES-ASAB
..            ...                                               ...
342            23  FACULTAD DEL MEDIO AMBIENTE Y RECURSOS NATURALES
343            23  FACULTAD DEL MEDIO AMBIENTE Y RECURSOS NATURALES
344            23  FACULTAD DEL MEDIO AMBIENTE Y RECURSOS NATURALES
345            23  FACULTAD DEL MEDIO AMBIENTE Y RECURSOS NATURALES
346            23  FACULTAD DEL MEDIO AMBIENTE Y RECURSOS NATURALES

     CODIGO_PROYECTO                            NOMBRE_PROYECTO       CODIGO  \
0                102                              ARTE DANZARIO  20212102020
1                104                            ARTES ESCENICAS  20212104019
2                104                            ARTES ESCENICAS  20212104020
3                 16                 ARTES PLASTICAS Y VISUALES  20212016015
4                 16                 ARTES PLASTICAS Y VISUALES  20212016018
..               ...                                        ...          ...
342              131  TECNOLOGIA EN LEVANTAMIENTOS TOPOGRAFICOS  20231131008
343              131  TECNOLOGIA EN LEVANTAMIENTOS TOPOGRAFICOS  20231131019
344              131  TECNOLOGIA EN LEVANTAMIENTOS TOPOGRAFICOS  20231131021
345               85        TECNOLOGÍA EN SANEAMIENTO AMBIENTAL  20212085018
346               85        TECNOLOGÍA EN SANEAMIENTO AMBIENTAL  20222085052

                              NOMBRE  PENSUM MODALIDAD ESTADO  \
0               CAÑAS FLOREZ JULIANA     371         S      J
1       VARGAS BAQUERO KAROL STEFANY     317         S      A
2         CAMACHO ANGEL LUIS ALBERTO     318         S      W
3              MENDEZ UNEME JENNIFER     280         S      U
4    SALAZAR RODRIGUEZ ANDRES FELIPE     264         S      U
..                               ...     ...       ...    ...
342    ORDOÑEZ PINEDA BRANDON ANDREY     343         S      J
343     OVIEDO GARCIA NIKOL DAYHANNA     343         S      J
344         MERCHAN PAMO JOSE YEINER     343         S      J
345  RODRIGUEZ ROJAS DIEGO ALEJANDRO     246         S      U
346          SIERRA CESPEDES DANIELA     246         S      W

                                DESC_ESTADO  ...  ACUERDO     NIVEL  \
0             PRUEBA ACADEMICA Y VACACIONES  ...  2011004  PREGRADO
1                    ESTUDIANTE MATRICULADO  ...  2011004  PREGRADO
2            ABANDONO - NO RENOVO MATRICULA  ...  2011004  PREGRADO
3    PERDIDA CALIDAD ESTUDIANTE ACUERDO 004  ...  2011004  PREGRADO
4    PERDIDA CALIDAD ESTUDIANTE ACUERDO 004  ...  2011004  PREGRADO
..                                      ...  ...      ...       ...
342           PRUEBA ACADEMICA Y VACACIONES  ...  2011004  PREGRADO
343           PRUEBA ACADEMICA Y VACACIONES  ...  2011004  PREGRADO
344           PRUEBA ACADEMICA Y VACACIONES  ...  2011004  PREGRADO
345  PERDIDA CALIDAD ESTUDIANTE ACUERDO 004  ...  2011004  PREGRADO
346          ABANDONO - NO RENOVO MATRICULA  ...  2011004  PREGRADO

    FEC_NACIMIENTO   FEC_GRADO  TIPO_DOCUMENTO  IDENTIFICACION  \
0         20020920  20191121.0              CC      1001457277
1         20020609  20191127.0              CC      1001273130
2         20020719  20191122.0              CC      1000350431
3         20030218  20191120.0              CC      1001066593
4         20010531         NaN              CC      1192803614
..             ...         ...             ...             ...
342       20060313  20221116.0              TI      1022345363
343       20040912  20221207.0              CC      1111263178
344       20040418  20201202.0              CC      1109840328
345       20030211  20211026.0              CC      1010062729
346       19960502         NaN              CC      1031164882

    VALOR_MATRICULA  FEC_NACIMIENTO_MOSTRAR  FALLECIDO  ruta
0            860732              2002-09-20          N  None
1            266802              2002-06-09          N  None
2            116001              2002-07-19          N  None
3            116001              2003-02-18          N  None
4            185602              2001-05-31          N  None
..              ...                     ...        ...   ...
342          185600              2006-03-13          N  None
343          185600              2004-09-12          N  None
344          185600              2004-04-18          N  None
345          185602              2003-02-11          N  None
346         2394240              1996-05-02          N  None

[347 rows x 25 columns]>

In [21]:
df.columns

Index(['COD_FACULTAD', 'FACULTAD', 'CODIGO_PROYECTO', 'NOMBRE_PROYECTO',
       'CODIGO', 'NOMBRE', 'PENSUM', 'MODALIDAD', 'ESTADO', 'DESC_ESTADO',
       'CODIGO_CRA', 'NOMBRE_CRA', 'EMAIL', 'TELEFONO', 'PROMEDIO', 'ACUERDO',
       'NIVEL', 'FEC_NACIMIENTO', 'FEC_GRADO', 'TIPO_DOCUMENTO',
       'IDENTIFICACION', 'VALOR_MATRICULA', 'FEC_NACIMIENTO_MOSTRAR',
       'FALLECIDO'],
      dtype='object')

In [23]:
def crear_carpeta(facultad, id):
    srcgen_folder = facultad + "/" + id
    if not exists(srcgen_folder):
        mkdir(srcgen_folder)

In [34]:
def crear_html(estudiante):
    with open(join(srcgen_folder, "%s_ha.html" % estudiante['IDENTIFICACION']), 'w') as f: f.write(template.render(entity=estudiante))

In [25]:
for i in range(len(df)):
    crear_carpeta(df.iloc[i]['FACULTAD'],str(df.iloc[i]['IDENTIFICACION']))

In [ ]:
template = jinja_env.get_template('historia_academica.template')

In [35]:
for i in range(len(df)):
    crear_html(df.iloc[i])

25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25